"""agregando borrado de posts

Revision ID: 3631e88fd6a2
Revises: d6672877cc3f
Create Date: 2025-11-05 08:53:47.750834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3631e88fd6a2'
down_revision = 'd6672877cc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
