"""agregando borrado de posts nuevos

Revision ID: 71554bbb6432
Revises: 3631e88fd6a2
Create Date: 2025-11-05 09:02:14.029467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71554bbb6432'
down_revision = '3631e88fd6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_1', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###
