"""quitando modificaciones de borrado

Revision ID: 8bd6e9200957
Revises: 71554bbb6432
Create Date: 2025-11-05 09:04:11.781622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bd6e9200957'
down_revision = '71554bbb6432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_3', 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
